config/routes.rb
Rails.application.routes.draw do
  resources :people do
    resources :phones
  end
  resources :people do
    resources :emails
  end
  resources :people do
    resources :addresses
  end
  devise_for :users
  root to: "people#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :person
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :person
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :phones
  has_many :emails
  has_many :addresses
  belongs_to :user
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :person
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :people
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_person
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET people/1/addresses
  def index
    @addresses = @person.addresses
  end

  # GET people/1/addresses/1
  def show
  end

  # GET people/1/addresses/new
  def new
    @address = @person.addresses.build
  end

  # GET people/1/addresses/1/edit
  def edit
  end

  # POST people/1/addresses
  def create
    @address = @person.addresses.build(address_params)

    if @address.save
      redirect_to(@address.person)
    else
      render action: 'new'
    end
  end

  # PUT people/1/addresses/1
  def update
    if @address.update_attributes(address_params)
      redirect_to(@address.person, notice: 'Address was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE people/1/addresses/1
  def destroy
    @address.destroy

    redirect_to(@person)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = current_user.people.find(params[:person_id])
    end

    def set_address
      @address = @person.addresses.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def address_params
      params.require(:address).permit(:street, :town, :zip_code, :state, :country, :person_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_person
  before_action :set_email, only: [:show, :edit, :update, :destroy]

  # GET people/1/emails
  def index
    @emails = @person.emails
  end

  # GET people/1/emails/1
  def show
  end

  # GET people/1/emails/new
  def new
    @email = @person.emails.build
  end

  # GET people/1/emails/1/edit
  def edit
  end

  # POST people/1/emails
  def create
    @email = @person.emails.build(email_params)

    if @email.save
      redirect_to(@email.person)
    else
      render action: 'new'
    end
  end

  # PUT people/1/emails/1
  def update
    if @email.update_attributes(email_params)
      redirect_to([@email.person, @email], notice: 'Email was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE people/1/emails/1
  def destroy
    @email.destroy

    redirect_to(@person)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = current_user.people.find(params[:person_id])
    end

    def set_email
      @email = @person.emails.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def email_params
      params.require(:email).permit(:email_address, :comment)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :authenticate_user!
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or /people.json
  def index
    @people = current_user.people
  end

  # GET /people/1 or /people/1.json
  def show
    @address = @person.addresses.build
    @email = @person.emails.build
    @phone = @person.phones.build
  end

  # GET /people/new
  def new
    @person = current_user.people.build
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = current_user.people.build(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to person_url(@person), notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to person_url(@person), notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = current_user.people.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:salutation, :first_name, :middle_name, :last_name, :ssn, :birth_date, :comment)
    end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_person
  before_action :set_phone, only: [:show, :edit, :update, :destroy]

  # GET people/1/phones
  def index
    @phones = @person.phones
  end

  # GET people/1/phones/1
  def show
  end

  # GET people/1/phones/new
  def new
    @phone = @person.phones.build
  end

  # GET people/1/phones/1/edit
  def edit
  end

  # POST people/1/phones
  def create
    @phone = @person.phones.build(phone_params)

    if @phone.save
      redirect_to(@phone.person)
    else
      render action: 'new'
    end
  end

  # PUT people/1/phones/1
  def update
    if @phone.update_attributes(phone_params)
      redirect_to([@phone.person, @phone], notice: 'Phone was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE people/1/phones/1
  def destroy
    @phone.destroy
    redirect_to(@person)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = current_user.people.find(params[:person_id])
    end

    def set_phone
      @phone = @person.phones.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def phone_params
      params.require(:phone).permit(:phone_number, :comment)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/addresses/_form.html.erb
<%= form_with(model: [@address.person, @address]) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :town %><br />
    <%= f.text_field :town %>
  </div>
  <div class="field">
    <%= f.label :zip_code %><br />
    <%= f.text_field :zip_code %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render 'form' %>

<%= link_to 'Show', [@address.person, @address] %> |
<%= link_to 'Back', @address.person %>

app/views/addresses/index.html.erb
<h1>Listing addresses</h1>

<table>
  <tr>
    <th>Street</th>
    <th>Town</th>
    <th>Zip code</th>
    <th>State</th>
    <th>Country</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @addresses.each do |address| %>
  <tr>
    <td><%= address.street %></td>
    <td><%= address.town %></td>
    <td><%= address.zip_code %></td>
    <td><%= address.state %></td>
    <td><%= address.country %></td>
    <td><%= link_to 'Show', [address.person, address] %></td>
    <td><%= link_to 'Edit', edit_person_address_path(address.person, address) %></td>
    <td><%= link_to 'Destroy', [address.person, address], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Address', new_person_address_path(params[:person_id]) %>

app/views/addresses/new.html.erb
<h1>New address</h1>

<%= render 'form' %>

<%= link_to 'Back', person_addresses_path(@address.person) %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Street:</b>
  <%= @address.street %>
</p>

<p>
  <b>Town:</b>
  <%= @address.town %>
</p>

<p>
  <b>Zip code:</b>
  <%= @address.zip_code %>
</p>

<p>
  <b>State:</b>
  <%= @address.state %>
</p>

<p>
  <b>Country:</b>
  <%= @address.country %>
</p>

<%= link_to 'Edit', edit_person_address_path(@address.person, @address) %> |
<%= link_to 'Back', @address.person %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InvoiceHomeAddressbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :salutation %>
    <%= form.text_field :salutation %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :middle_name %>
    <%= form.text_field :middle_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :ssn %>
    <%= form.text_field :ssn %>
  </div>

  <div class="field">
    <%= form.label :birth_date %>
    <%= form.text_field :birth_date %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Salutation</th>
      <th>First name</th>
      <th>Middle name</th>
      <th>Last name</th>
      <th>Ssn</th>
      <th>Birth date</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.salutation %></td>
        <td><%= person.first_name %></td>
        <td><%= person.middle_name %></td>
        <td><%= person.last_name %></td>
        <td><%= person.ssn %></td>
        <td><%= person.birth_date %></td>
        <td><%= person.comment %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Salutation:</strong>
  <%= @person.salutation %>
</p>

<p>
  <strong>First name:</strong>
  <%= @person.first_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @person.middle_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @person.last_name %>
</p>

<p>
  <strong>Ssn:</strong>
  <%= @person.ssn %>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @person.birth_date %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @person.comment %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

<hr>
<h1>New address</h1>
<%= render 'addresses/form' %>

<hr>
<h1>Listing addresses</h1>

<table>
  <tr>
    <th>Street</th>
    <th>Town</th>
    <th>Zip code</th>
    <th>State</th>
    <th>Country</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @person.addresses.each do |address| %>
  <% if address.persisted? %>
    <tr>
      <td><%= address.street %></td>
      <td><%= address.town %></td>
      <td><%= address.zip_code %></td>
      <td><%= address.state %></td>
      <td><%= address.country %></td>
      <td><%= link_to 'Show', [address.person, address] %></td>
      <td><%= link_to 'Edit', edit_person_address_path(address.person, address) %></td>
      <td><%= link_to 'Destroy', [address.person, address], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
<% end %>
</table>
<br />
<%= link_to 'New Address', new_person_address_path(@person.id) %>

<hr>
<h1>New phone</h1>
<%= render 'phones/form' %>

<hr>
<h1>Listing phones</h1>

<table>
  <tr>
    <th>Phone number</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @person.phones.each do |phone| %>
  <% if phone.persisted? %>
    <tr>
      <td><%= phone.phone_number %></td>
      <td><%= phone.comment %></td>
      <td><%= link_to 'Show', [phone.person, phone] %></td>
      <td><%= link_to 'Edit', edit_person_phone_path(phone.person, phone) %></td>
      <td><%= link_to 'Destroy', [phone.person, phone], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
<% end %>
</table>

<br />

<%= link_to 'New Phone', new_person_phone_path(@person.id) %>


<hr>
<h1>New email</h1>
<%= render 'emails/form' %>

<hr>
<h1>Listing emails</h1>

<table>
  <tr>
    <th>Email address</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @person.emails.each do |email| %>
  <% if email.persisted? %>
    <tr>
      <td><%= email.email_address %></td>
      <td><%= email.comment %></td>
      <td><%= link_to 'Show', [email.person, email] %></td>
      <td><%= link_to 'Edit', edit_person_email_path(email.person, email) %></td>
      <td><%= link_to 'Destroy', [email.person, email], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
<% end %>
</table>

<br />

<%= link_to 'New Email', new_person_email_path(@person.id) %>

app/views/phones/_form.html.erb
<%= form_with(model: [@phone.person, @phone]) do |f| %>
  <% if @phone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phone.errors.count, "error") %> prohibited this phone from being saved:</h2>

      <ul>
      <% @phone.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phones/edit.html.erb
<h1>Editing phone</h1>

<%= render 'form' %>

<%= link_to 'Show', [@phone.person, @phone] %> |
<%= link_to 'Back', @phone.person %>

app/views/phones/index.html.erb
<h1>Listing phones</h1>

<table>
  <tr>
    <th>Phone number</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @phones.each do |phone| %>
  <tr>
    <td><%= phone.phone_number %></td>
    <td><%= phone.comment %></td>
    <td><%= link_to 'Show', [phone.person, phone] %></td>
    <td><%= link_to 'Edit', edit_person_phone_path(phone.person, phone) %></td>
    <td><%= link_to 'Destroy', [phone.person, phone], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Phone', new_person_phone_path(params[:person_id]) %>

app/views/phones/new.html.erb
<h1>New phone</h1>

<%= render 'form' %>

<%= link_to 'Back', person_phones_path(@phone.person) %>

app/views/phones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Phone number:</b>
  <%= @phone.phone_number %>
</p>

<p>
  <b>Comment:</b>
  <%= @phone.comment %>
</p>

<%= link_to 'Edit', edit_person_phone_path(@phone.person, @phone) %> |
<%= link_to 'Back', @phone.person %>